BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Users" (
	"ID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"Imie"	TEXT NOT NULL,
	"Nazwisko"	TEXT NOT NULL,
	"Password"	TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS "Nazwiska" ON "Users" (
	"Nazwisko"	ASC
);
COMMIT;
