BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Users";
CREATE TABLE IF NOT EXISTS "Users" (
	"ID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"Username"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL DEFAULT 'PASSWORD'
);
COMMIT;
