BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Hasla";
CREATE TABLE IF NOT EXISTS "Hasla" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Username"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL
);
COMMIT;
